### 1. How are coefficients affected?

In [1]:
from sklearn.datasets import load_diabetes
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [13]:
data = load_diabetes()
df = pd.DataFrame(data.data,columns=data.feature_names)
df['TARGET'] = data.target
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,TARGET
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [14]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('TARGET',axis=1),df['TARGET'],test_size=0.2,random_state=42)

In [15]:
from sklearn.linear_model import Lasso

In [16]:
coeffs = []
r2_scores = []
for i in (0,0.1,1,10):
    lasso = Lasso(alpha=i)
    lasso.fit(x_train,y_train)
    coeffs.append(lasso.coef_.tolist())
    y_pred = lasso.predict(x_test)
    r2_scores.append(r2_score(y_test,y_pred))

c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.063e+05, tolerance: 2.145e+02
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

In [17]:
print(coeffs)
print(r2_scores)

[[37.90402137856623, -241.96436229925743, 542.428758647441, 347.7038438652992, -931.4888381959984, 518.0622710331813, 163.419979552481, 275.31790051957074, 736.1988559877806, 48.67065746354233], [0.0, -152.6647792342514, 552.6977752929224, 303.36515790671865, -81.36500663537598, -0.0, -229.2557763858321, 0.0, 447.9195251841385, 29.64261703820769], [0.0, -0.0, 413.4318479231421, 34.830515180609865, 0.0, 0.0, -0.0, 0.0, 258.15289363124595, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
[0.4526027630436198, 0.4718547867276227, 0.3575918767219113, -0.011962984778542296]

In [18]:
# we can see that as we increase the value of alpha, the coefficients are getting smaller and at alpha = 10, all the coefficients are zero

### 2. Higher Coefficients are affected more

In [19]:
alphas = [0,0.0001,0.001,0.01,0.1,1,10,100,1000,10000]
coefs = []
for i in range(len(alphas)):
    lasso = Lasso(alpha=alphas[i])
    lasso.fit(x_train,y_train)
    coefs.append(lasso.coef_.tolist())

c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.063e+05, tolerance: 2.145e+02
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

In [22]:
arr = np.array(coefs)
coef_df = pd.DataFrame(arr,columns=data.feature_names)
coef_df['alpha'] = alphas
coef_df.set_index('alpha')

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
alpha,,,,,,,,,,
0.0000,37.904021,-241.964362,542.428759,347.703844,-931.488838,518.062271,163.419980,275.317901,736.198856,48.670657
0.0001,37.891667,-241.878244,542.524544,347.624893,-924.832045,513.033268,160.224210,274.036385,733.762619,48.690013
0.0010,37.780431,-241.103200,543.386372,346.914418,-864.934721,467.782935,131.468467,262.504646,711.841733,48.864159
0.0100,35.347451,-231.906664,551.303242,341.313469,-483.567140,165.990532,-25.834899,216.875803,566.815003,49.702475
0.1000,0.000000,-152.664779,552.697775,303.365158,-81.365007,-0.000000,-229.255776,0.000000,447.919525,29.642617
1.0000,0.000000,-0.000000,413.431848,34.830515,0.000000,0.000000,-0.000000,0.000000,258.152894,0.000000
10.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
100.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1000.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10000.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [23]:
# if we increase the lamda value then the coefficients are decreasin rapidly and it can reach to 0

3. Bias-Variance Trade-offIncreasing $\lambda$ (alpha): Reduces overfitting.Bias: Increases as $\lambda$ grows because the model becomes less flexible.Variance: Decreases as coefficients shrink.Goal: Pick an intermediate $\lambda$ where bias and variance reach an optimal balance point.

4. Loss Function Space & SparsityShape Distortion: Increasing $\lambda$ distorts the loss function curve unevenly rather than just smoothly shifting it.Hard Zero Point: Higher $\lambda$ pulls the minimum point of the loss function directly onto the axis where the coefficient is exactly zero.Feature Selection: Once a coefficient hits zero, further increases in $\lambda$ keep it locked precisely at zero. This is why Lasso creates true sparsity and acts as an automatic feature selector.