## Categorical Encoding
we use ordinal encoding if input data is categorical and if output dta is categorical then we use label encoding

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('customer.csv')

In [9]:
df.head(3)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   gender     50 non-null     str
 2   review     50 non-null     str
 3   education  50 non-null     str
 4   purchased  50 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.1 KB

In [11]:
df = df.iloc[:, 2:]
df.head(2)

    review education purchased
0  Average    School        No
1     Poor        UG        No