## Normalization:

their are 4 types of normalization

i) MinMaxScalling

ii) Mean Normalization

iii) Max Abolute

iv) Robust Scalling

### Mean Normalization

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('wine_data.csv',header=None,usecols=[0,1,2])

In [3]:
df.head(3)

   0      1     2
0  1  14.23  1.71
1  1  13.20  1.78
2  1  13.16  2.36

In [4]:
df.columns = ['Class label','Alcohol','Malic acid']
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Class label  178 non-null    int64
 1   Alcohol      178 non-null    float64
 2   Malic acid   178 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 4.3 KB

In [5]:
X = df.iloc[:,1:]
Y = df.iloc[:,0]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [14]:
x_train.head(3)

     Alcohol  Malic acid
22     13.71        1.86
108    12.22        1.29
175    13.27        4.28

In [17]:
def transformation(x):
    for i in range(len(x)):
        x[i] = (x[i] - np.mean(x))/(np.max(x)-np.min(x))
    return x

In [64]:
def mean_normalization(d):
    alcohol = d.iloc[:,0].to_numpy().copy()
    malic_acid = d.iloc[:,1].to_numpy().copy()
    transformation_alcohol = transformation(alcohol)
    transformation_malic_acid = transformation(malic_acid)
    data = np.column_stack([transformation_alcohol,transformation_malic_acid])
    return pd.DataFrame(data,columns=d.columns)

In [65]:
x_train_scaled = mean_normalization(x_train)
x_test_scaled = mean_normalization(x_test)

In [67]:
np.round(x_train_scaled.describe(),1)

       Alcohol  Malic acid
count    124.0       124.0
mean       0.4         0.2
std        0.3         0.3
min       -0.0        -0.2
25%        0.2         0.0
50%        0.5         0.2
75%        0.7         0.4
max        1.0         0.9