In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head(3)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    str
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), str(1)
memory usage: 15.8 KB

In [5]:
df = df.iloc[:,2:]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

## Train Test Split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.iloc[:,1:]
Y = df.iloc[:,0]

In [9]:
X.info()
Y.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EstimatedSalary  400 non-null    int64
 1   Purchased        400 non-null    int64
dtypes: int64(2)
memory usage: 6.4 KB
<class 'pandas.Series'>
RangeIndex: 400 entries, 0 to 399
Series name: Age
Non-Null Count  Dtype
--------------  -----
400 non-null    int64
dtypes: int64(1)
memory usage: 3.3 KB

In [10]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

## Standard Scaler

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()
scaler.fit(x_train) #here we calculate the mean and standard deviation of the training data and store it in the scaler object
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [17]:
x_train_scaled

array([[-0.38634438, -0.74898305],
       [-1.22993871,  1.3351437 ],
       [ 1.853544  ,  1.3351437 ],
       [-0.90995465, -0.74898305],
       [-1.28811763,  1.3351437 ],
       [ 1.44629156,  1.3351437 ],
       [-0.53179168, -0.74898305],
       [ 0.10817643,  1.3351437 ],
       [ 0.45724994, -0.74898305],
       [ 0.31180264, -0.74898305],
       [ 0.45724994,  1.3351437 ],
       [-0.47361276, -0.74898305],
       [-0.32816546, -0.74898305],
       [ 0.28271318, -0.74898305],
       [-1.57901222, -0.74898305],
       [ 0.25362372, -0.74898305],
       [ 1.73718616,  1.3351437 ],
       [-0.18271817, -0.74898305],
       [ 2.11534913,  1.3351437 ],
       [ 1.21357589,  1.3351437 ],
       [ 1.50447048,  1.3351437 ],
       [ 0.02090805, -0.74898305],
       [-1.31720709,  1.3351437 ],
       [-1.49174384, -0.74898305],
       [-0.5899706 , -0.74898305],
       [ 2.31897535,  1.3351437 ],
       [-1.20084925,  1.3351437 ],
       [ 1.06812859,  1.3351437 ],
       [-1.05540195,  1.3351437 ],
       [-0.26998655, -0.74898305],
       [-1.14267033, -0.74898305],
       [ 0.02090805, -0.74898305],
       [-0.90995465,  1.3351437 ],
       [-0.90995465,  1.3351437 ],
       [ 1.21357589,  1.3351437 ],
       [-1.46265438, -0.74898305],
       [-1.54992276, -0.74898305],
       [ 0.66087616,  1.3351437 ],
       [-0.47361276, -0.74898305],
       [-0.26998655, -0.74898305],
       [ 0.13726589, -0.74898305],
       [ 0.28271318, -0.74898305],
       [-1.28811763,  1.3351437 ],
       [ 1.09721805,  1.3351437 ],
       [-1.37538601,  1.3351437 ],
       [-1.22993871, -0.74898305],
       [ 0.13726589, -0.74898305],
       [-0.15362871, -0.74898305],
       [ 0.02090805, -0.74898305],
       [ 2.20261751,  1.3351437 ],
       [ 0.74814454,  1.3351437 ],
       [ 0.54451832, -0.74898305],
       [ 0.71905508,  1.3351437 ],
       [-1.40447546, -0.74898305],
       [-0.32816546, -0.74898305],
       [ 0.54451832, -0.74898305],
       [ 0.28271318,  1.3351437 ],
       [ 1.09721805,  1.3351437 ],
       [ 0.74814454, -0.74898305],
       [ 1.24266535,  1.3351437 ],
       [-1.22993871, -0.74898305],
       [-1.31720709, -0.74898305],
       [ 0.54451832,  1.3351437 ],
       [-1.60810168, -0.74898305],
       [ 0.25362372, -0.74898305],
       [ 2.05717021, -0.74898305],
       [ 1.35902318, -0.74898305],
       [ 0.02090805, -0.74898305],
       [ 0.45724994, -0.74898305],
       [ 0.25362372, -0.74898305],
       [ 0.39907102, -0.74898305],
       [-0.15362871, -0.74898305],
       [ 0.10817643,  1.3351437 ],
       [-1.60810168, -0.74898305],
       [ 0.28271318, -0.74898305],
       [-0.79359682, -0.74898305],
       [ 2.28988589,  1.3351437 ],
       [-0.82268628, -0.74898305],
       [ 0.98086021,  1.3351437 ],
       [-1.08449141, -0.74898305],
       [-1.11358087,  1.3351437 ],
       [ 2.08625967,  1.3351437 ],
       [-0.24089709, -0.74898305],
       [ 2.26079643,  1.3351437 ],
       [-0.38634438, -0.74898305],
       [-0.5899706 , -0.74898305],
       [-0.50270222, -0.74898305],
       [-0.93904411, -0.74898305],
       [-1.17175979, -0.74898305],
       [ 0.04999751, -0.74898305],
       [-1.60810168, -0.74898305],
       [-0.06636033, -0.74898305],
       [-0.50270222, -0.74898305],
       [-1.31720709, -0.74898305],
       [ 0.54451832, -0.74898305],
       [ 0.04999751, -0.74898305],
       [ 1.53355994,  1.3351437 ],
       [ 0.3408921 , -0.74898305],
       [-0.21180763, -0.74898305],
       [-1.40447546,  1.3351437 ],
       [-0.61906006, -0.74898305],
       [-1.31720709, -0.74898305],
       [ 0.13726589, -0.74898305],
       [ 1.35902318,  1.3351437 ],
       [ 0.3408921 , -0.74898305],
       [ 0.28271318, -0.74898305],
       [ 1.76627562,  1.3351437 ],
       [ 2.11534913,  1.3351437 ],
       [-0.4445233 , -0.74898305],
       [-0.79359682, -0.74898305],
       [-0.26998655, -0.74898305],
       [ 0.74814454,  1.3351437 ],
       [ 0.36998156,  1.3351437 ],
       [-0.4445233 , -0.74898305],
       [ 2.14443859,  1.3351437 ],
       [ 0.98086021,  1.3351437 ],
       [ 0.25362372, -0.74898305],
       [ 0.83541291,  1.3351437 ],
       [-0.29907601,  1.3351437 ],
       [ 1.94081237,  1.3351437 ],
       [-0.79359682, -0.74898305],
       [ 0.02090805, -0.74898305],
       [-1.43356492,  1.3351437 ],
       [ 2.31897535,  1.3351437 ],
       [-0.00818141,  1.3351437 ],
       [ 0.39907102, -0.74898305],
       [ 0.04999751, -0.74898305],
       [-0.53179168, -0.74898305],
       [-0.29907601, -0.74898305],
       [-0.12453925, -0.74898305],
       [ 2.14443859,  1.3351437 ],
       [-0.26998655, -0.74898305],
       [-1.05540195, -0.74898305],
       [ 0.13726589, -0.74898305],
       [ 1.35902318,  1.3351437 ],
       [-0.53179168, -0.74898305],
       [ 0.02090805, -0.74898305],
       [ 0.51542886,  1.3351437 ],
       [-1.08449141,  1.3351437 ],
       [ 1.96990183,  1.3351437 ],
       [-0.5899706 ,  1.3351437 ],
       [-0.03727087, -0.74898305],
       [ 2.20261751,  1.3351437 ],
       [ 0.3408921 , -0.74898305],
       [-0.67723898, -0.74898305],
       [-1.40447546, -0.74898305],
       [-0.99722303, -0.74898305],
       [-0.7354179 ,  1.3351437 ],
       [-0.79359682, -0.74898305],
       [ 0.89359183,  1.3351437 ],
       [-0.38634438, -0.74898305],
       [ 1.21357589, -0.74898305],
       [ 0.28271318, -0.74898305],
       [-1.22993871,  1.3351437 ],
       [ 0.13726589, -0.74898305],
       [ 0.04999751, -0.74898305],
       [-0.29907601, -0.74898305],
       [ 1.7080967 ,  1.3351437 ],
       [ 0.4863394 ,  1.3351437 ],
       [ 1.24266535,  1.3351437 ],
       [-1.37538601,  1.3351437 ],
       [-1.11358087, -0.74898305],
       [-1.5208333 , -0.74898305],
       [-0.53179168, -0.74898305],
       [-1.5208333 , -0.74898305],
       [ 0.51542886, -0.74898305],
       [-1.02631249,  1.3351437 ],
       [ 0.54451832, -0.74898305],
       [ 0.777234  ,  1.3351437 ],
       [ 0.07908697,  1.3351437 ],
       [-0.06636033, -0.74898305],
       [ 0.04999751, -0.74898305],
       [-0.29907601, -0.74898305],
       [ 1.853544  ,  1.3351437 ],
       [ 0.39907102, -0.74898305],
       [ 0.51542886,  1.3351437 ],
       [-0.35725492, -0.74898305],
       [ 1.38811264,  1.3351437 ],
       [ 0.51542886,  1.3351437 ],
       [ 0.3408921 , -0.74898305],
       [ 1.88263345,  1.3351437 ],
       [ 0.45724994, -0.74898305],
       [-1.25902817, -0.74898305],
       [-0.79359682, -0.74898305],
       [ 0.51542886, -0.74898305],
       [-0.32816546, -0.74898305],
       [-1.11358087,  1.3351437 ],
       [-0.82268628,  1.3351437 ],
       [ 0.60269724,  1.3351437 ],
       [-0.76450736, -0.74898305],
       [-0.76450736, -0.74898305],
       [ 2.28988589,  1.3351437 ],
       [ 0.25362372, -0.74898305],
       [-0.29907601, -0.74898305],
       [-1.37538601, -0.74898305],
       [-0.56088114, -0.74898305],
       [-0.00818141, -0.74898305],
       [ 1.73718616,  1.3351437 ],
       [-0.76450736, -0.74898305],
       [ 1.4172021 ,  1.3351437 ],
       [ 0.16635535, -0.74898305],
       [ 0.04999751, -0.74898305],
       [ 0.02090805,  1.3351437 ],
       [ 0.51542886, -0.74898305],
       [ 1.62082832,  1.3351437 ],
       [ 0.13726589, -0.74898305],
       [-0.35725492, -0.74898305],
       [ 1.30084427, -0.74898305],
       [ 0.07908697, -0.74898305],
       [ 1.09721805,  1.3351437 ],
       [ 0.4863394 , -0.74898305],
       [-0.47361276, -0.74898305],
       [-1.57901222, -0.74898305],
       [ 0.10817643, -0.74898305],
       [-0.90995465, -0.74898305],
       [-0.00818141,  1.3351437 ],
       [-1.17175979,  1.3351437 ],
       [-0.5899706 , -0.74898305],
       [ 2.23170697,  1.3351437 ],
       [ 0.19544481, -0.74898305],
       [ 0.25362372, -0.74898305],
       [-1.08449141, -0.74898305],
       [-0.70632844,  1.3351437 ],
       [-0.32816546, -0.74898305],
       [-0.12453925, -0.74898305],
       [-0.21180763, -0.74898305],
       [-1.54992276, -0.74898305],
       [-1.08449141, -0.74898305],
       [ 0.36998156, -0.74898305],
       [-0.93904411,  1.3351437 ],
       [ 0.3408921 , -0.74898305],
       [-0.32816546, -0.74898305],
       [-1.54992276, -0.74898305],
       [-0.67723898,  1.3351437 ],
       [-1.17175979,  1.3351437 ],
       [-0.15362871, -0.74898305],
       [-0.99722303,  1.3351437 ],
       [ 0.04999751,  1.3351437 ],
       [-0.38634438, -0.74898305],
       [ 1.27175481, -0.74898305],
       [-0.82268628, -0.74898305],
       [-0.21180763, -0.74898305],
       [ 0.98086021,  1.3351437 ],
       [-0.53179168, -0.74898305],
       [-1.08449141,  1.3351437 ],
       [-1.20084925,  1.3351437 ],
       [ 0.25362372,  1.3351437 ],
       [-0.26998655, -0.74898305],
       [ 0.10817643, -0.74898305],
       [ 0.57360778, -0.74898305],
       [-1.60810168, -0.74898305],
       [ 0.22453427, -0.74898305],
       [ 0.39907102, -0.74898305],
       [-0.5899706 , -0.74898305],
       [ 1.76627562,  1.3351437 ],
       [ 0.04999751, -0.74898305],
       [-1.37538601, -0.74898305],
       [-1.46265438, -0.74898305],
       [ 0.54451832, -0.74898305],
       [ 0.28271318, -0.74898305],
       [-0.67723898, -0.74898305],
       [ 0.57360778, -0.74898305],
       [ 0.04999751, -0.74898305],
       [ 1.32993372, -0.74898305],
       [ 1.50447048,  1.3351437 ],
       [ 0.36998156, -0.74898305],
       [-0.21180763, -0.74898305],
       [ 0.57360778,  1.3351437 ],
       [-0.32816546, -0.74898305],
       [-1.5208333 , -0.74898305],
       [ 0.13726589,  1.3351437 ],
       [ 0.31180264, -0.74898305],
       [ 1.03903913,  1.3351437 ],
       [-0.4445233 , -0.74898305],
       [ 1.38811264,  1.3351437 ],
       [-0.82268628,  1.3351437 ],
       [-0.4445233 , -0.74898305],
       [ 1.853544  , -0.74898305],
       [-1.22993871,  1.3351437 ],
       [-0.29907601, -0.74898305],
       [ 0.98086021,  1.3351437 ],
       [-0.35725492, -0.74898305],
       [-1.11358087, -0.74898305],
       [ 0.04999751, -0.74898305],
       [-1.11358087, -0.74898305],
       [-1.46265438,  1.3351437 ],
       [-0.85177573, -0.74898305],
       [-0.67723898, -0.74898305],
       [-1.5208333 , -0.74898305],
       [ 1.88263345,  1.3351437 ],
       [ 1.00994967,  1.3351437 ],
       [ 0.25362372,  1.3351437 ],
       [ 1.853544  ,  1.3351437 ],
       [-0.61906006,  1.3351437 ],
       [ 2.05717021,  1.3351437 ],
       [ 0.86450237,  1.3351437 ],
       [ 0.02090805, -0.74898305],
       [-1.28811763, -0.74898305],
       [ 0.19544481, -0.74898305],
       [-0.56088114,  1.3351437 ],
       [-0.38634438, -0.74898305],
       [ 1.59173886,  1.3351437 ],
       [ 0.10817643, -0.74898305],
       [-0.35725492, -0.74898305],
       [-0.7354179 , -0.74898305],
       [-0.47361276, -0.74898305],
       [-0.96813357, -0.74898305],
       [ 0.07908697, -0.74898305],
       [ 0.42816048, -0.74898305],
       [-0.56088114, -0.74898305],
       [-0.79359682, -0.74898305],
       [ 0.04999751, -0.74898305],
       [-0.99722303,  1.3351437 ],
       [-1.40447546,  1.3351437 ],
       [ 0.04999751, -0.74898305],
       [-1.25902817, -0.74898305],
       [-1.02631249, -0.74898305],
       [ 1.82445454, -0.74898305],
       [ 0.19544481, -0.74898305],
       [ 0.45724994, -0.74898305]])

In [18]:
print(type(x_train_scaled))

<class 'numpy.ndarray'>

In [19]:
#because the output in the form of numpy array so it's very hard
#for us to understand the data columns names that cause difficulty in feature engineering
#so we just convert the numpy array into pandas dataframe and assign the column names to it
#as the column names are same as the x_train/x_test
x_train_scaled = pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled,columns=x_test.columns)

describe the x_train data frame that return all data related to count,mean,standard deviation etc and return the result in the round of 1 decimal place

In [20]:
np.round(x_train.describe(),1)

       EstimatedSalary  Purchased
count            320.0      320.0
mean           70281.2        0.4
std            34430.6        0.5
min            15000.0        0.0
25%            43000.0        0.0
50%            71000.0        0.0
75%            88000.0        1.0
max           150000.0        1.0

In [21]:
np.round(x_train_scaled.describe(),1)

       EstimatedSalary  Purchased
count            320.0      320.0
mean               0.0        0.0
std                1.0        1.0
min               -1.6       -0.7
25%               -0.8       -0.7
50%                0.0       -0.7
75%                0.5        1.3
max                2.3        1.3