In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('train2.csv')

In [11]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [12]:

df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [13]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    str
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(2)
memory usage: 55.8 KB

In [15]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
model = LogisticRegression()

In [25]:
param_grid = {
    "C": [0.1, 1, 10],
    "l1_ratio": [0, 0.5, 1],   # replaces penalty
    "solver": ["saga"],        # supports elasticnet
    "max_iter": [200, 500]
}

In [27]:
grid = GridSearchCV(estimator=model,param_grid=param_grid,cv=5)

In [28]:
grid.fit(x_train,y_train)

ValueError:
All the 90 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
90 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1191, in fit
    X, y = validate_data(
           ~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<5 lines>...
        accept_large_sparse=solver not in ["liblinear", "sag", "saga"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\utils\validation.py", line 2919, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\utils\validation.py", line 1314, in check_X_y
    X = check_array(
        X,
    ...<12 lines>...
        input_name="X",
    )
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\utils\validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\sklearn\utils\_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "c:\Users\rajmu\OneDrive\Desktop\ML\Scikit_Learn\.venv\Lib\site-packages\pandas\core\generic.py", line 2039, in __array__
    arr = np.asarray(values, dtype=dtype)
ValueError: could not convert string to float: 'male'